trainer:
  accelerator: gpu      # or "cpu"
  devices: [1]
  max_epochs: 100
  default_root_dir: ./logs  # where to save logs/checkpoints
  precision: 16-mixed
  callbacks:
    histogram_logger:
      enabled: True
      log_every_n_epochs: 1
      layers_to_log: [temporal_transformer, decoder]
  early_stopper_handler:
    min_delta: 0.01
    patience: 5
    mode: min
    monitor: val_loss
  checkpoint_handler:
    dir: ./checkpoints
    monitor: val_loss
    mode: min
  logger:
    enabled: true
    dir: ./logs
    name: sparknet_experiment

global_params:
  seed: 42
  learning_rate: 0.0001
  loss_type: null
  pos_weight: null  # Only applies when using loss_type == weighted_bce
  focal:
    alpha: 0.25
    gamma: 2.0
